[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Armonia Meta Chain"
authors = [{name = "Ray", email = "ray@gmail"}]
dynamic = ["version", "description"]
